# Generated by Django 5.2.7 on 2025-11-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perfil", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="active_directory",
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
