# Generated by Django 5.2.7 on 2025-11-07 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gerenciador", "0002_userprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
