# Generated by Django 5.2.7 on 2025-11-07 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gerenciador", "0003_delete_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="transferlog",
            name="file_size",
            field=models.BigIntegerField(default=0),
        ),
    ]
